Add documentation on lldb-mi for cpptools
WardenGnaw/vscode-docs pull request #1
Opened 2020-01-31 00:52 UTC by WardenGnaw

2020-01-31 00:52 UTC, WardenGnaw commented
@pieandcakes Any comments?

2020-02-11 22:13 UTC, pieandcakes requested changes

2020-02-11 22:13 UTC, pieandcakes commented on docs/cpp/lldb-mi.md
> +The debug adapter for the C/C++ extension utilizes the machine interface mode for both gdb and lldb. To use this interface in lldb, we utilize `lldb-mi`. We build and ship this executable which has a
`... We build and ship this executable which has a dependency on `LLDB.framework` which is part of XCode.` or something to that effect.

2020-02-11 22:13 UTC, pieandcakes commented on docs/cpp/lldb-mi.md
> +    3. Confirm prompt
`Install.` has a period but the others don't. Also is it the license prompt? maybe make this a little clearer.

2020-02-11 22:13 UTC, pieandcakes commented on docs/cpp/lldb-mi.md
> +If you wish to use a LLDB.framework that is not installed the way described above, you can copy the `lldb-mi` executable in `~/.vscode/extensions/ms.vscode-cpptools-<version>/debugAdapters/lldb/bin`
maybe phrase this as `using an LLDB.Framework` that is not installed via XCode ? and just say you need to specify the full path to the `lldbi-mi` executable in the `miDebuggerPath` field in `launch.json`

2020-02-11 22:13 UTC, pieandcakes commented on docs/cpp/lldb-mi.md
> +Assuming you have `LLDB.framework` at `"/Users/default/example/"`
Instead of `Assuming` make this a `You have LLDB.Framework located at ...` and then have a step to copy `lldb-mi` in there also.

2020-02-11 22:13 UTC, pieandcakes commented on docs/cpp/lldb-mi.md
> +    "miDebuggerPath": "/Users/default/example/lldb-mi"
Add a section about building/running their own lldb-mi by specifying the path to the lldb-mi in launch.json

2020-02-11 22:13 UTC, pieandcakes commented on docs/cpp/lldb-mi.md
> +PageTitle: How to setup debugging on macOS with LLDB-MI
I think `set up` is two words in this context, which is different from the TOCTitle

2020-02-11 22:13 UTC, pieandcakes commented on docs/cpp/lldb-mi.md
> +# Setup
Explain that we are building lldb-mi based off of which repository.

2020-02-11 22:46 UTC, pieandcakes commented on docs/cpp/lldb-mi.md
> +If you wish to use a LLDB.framework that is not installed the way described above, you can copy the `lldb-mi` executable in `~/.vscode/extensions/ms.vscode-cpptools-<version>/debugAdapters/lldb-mi/bi
instead of "the way described above" i would just say "with XCode" in case you reorder the "above" and forget about this sentence.

2020-02-11 22:46 UTC, pieandcakes commented on docs/cpp/lldb-mi.md
> +If you wish to use a LLDB.framework that is not installed the way described above, you can copy the `lldb-mi` executable in `~/.vscode/extensions/ms.vscode-cpptools-<version>/debugAdapters/lldb-mi/bi
`right next to where the `LLDB.framework` folder is located.` right? you want it next to the framework folder?

2020-02-11 22:46 UTC, pieandcakes commented on docs/cpp/lldb-mi.md
> +You have `LLDB.framework` located at `/Users/default/example/`
folder?

2020-02-11 22:46 UTC, pieandcakes commented on docs/cpp/lldb-mi.md
> +If you built your own `lldb-mi`, you can use it by setting `miDebuggerPath` to the executable.
you can use it by setting `miDebuggerPath` to the full path of the executable

2020-02-12 01:16 UTC, pieandcakes approved these changes

2020-02-12 01:40 UTC, closed without merging

2020-02-12 01:40 UTC, WardenGnaw commented
Made PR upstream.